### ISSUE TITLE
Event datetime validation seems to ignore date differences

### ISSUE THREAD

**Issue by Rumperuu** [vincentmdealmeida/DEMOS2#18]
The datetime validation when creating a new event seems to ignore the difference in dates when comparing times, and throws up an error stating that 'the start date must be before the end date and the end after the start date' if, for example, an event is set to start on the 24th August at 12:00 and end on the 24th Setepmber at 11:55.

**Comment by vince0656** [comment]
I can’t seem to reproduce this bug and it seems to be working ok on my machine. Are you still having this issue Ben?

**Comment by Rumperuu** [comment]
When I was creating my merge request I realised that I had changed the way the dates were handled in the interests of brevity, which must have been the source of the issue for me.

![dateobjs](https://user-images.githubusercontent.com/5621904/44792156-2f800600-ab9b-11e8-99ee-1c595db705d7.png)
